/**
 * Endgame database: the exact value of every position with few enough
 * pieces, generated by `dbgen` (see dbgen/README.md).
 *
 * One byte per position, always with white to move; a black-to-move
 * position is mirrored before the lookup. The byte is a budget threshold,
 * not a plain win/draw/loss:
 *
 *   0        draw whatever the draw counter says
 *   1..30    win, needs a counter budget of at least this many plies
 *   32..62   loss, the budget it needs is the value minus 32
 *
 * The budget is `DRAW_PLIES - plies`, the quiet king plies the position
 * still has before RULES.md draws the game, so a probe answers the rule
 * exactly at any counter state. The threshold doubles as the distance to
 * the next capture or man move: scoring a win as `DB_WIN - threshold`
 * makes the search prefer the line that converts soonest instead of
 * shuffling kings until the counter runs out.
 *
 * Tables are loaded one slice (material class) at a time, and a slice is
 * a header, a block offset table and blocks of `1 << blockShift`
 * positions, each raw deflate. A probe inflates one block and keeps it,
 * so nothing is held uncompressed that the search does not touch.
 *
 * `dbProbe` is only correct at a node where the side to move has no
 * capture: captures are mandatory, and the generator marks those
 * positions as don't-care, filling them with whatever compresses best.
 */
import { lsb, popcount, reverse32 } from './bitboard.ts'
import { inflateRaw } from './inflate.ts'
import { WHITE } from './position.ts'
import { ttClear } from './tt.ts'
import { DRAW_SCORE } from './score.ts'
import { DRAW_PLIES } from './status.ts'

/** Returned when the position is not in the loaded tables. */
export const DB_UNKNOWN = 0x7fffffff
/**
 * Score of a database win that converts at once. Above every evaluation
 * and below every mate score, so a proven mate still wins the comparison.
 */
export const DB_WIN = 25000
/**
 * The smallest winning score the database returns: a win that needs the
 * whole counter. Anything at least this high is a proven win, database or
 * mate, which is what the screen reads to know the game is decided.
 */
export const DB_WIN_MIN = DB_WIN - DRAW_PLIES
/**
 * How far a position the database calls drawn may stray from
 * `DRAW_SCORE`, so the engine still holds material where every move
 * draws. It stays small enough for such a position to read as level.
 */
export const DB_DRAW_BAND = 32

const DB_DRAW = 0
const DB_LOSS_BASE = 32

const MAGIC = 0x3142_4b44 // "DKB1", little endian

/** More pieces than a board holds: the probe answers for all it has. */
const NO_LIMIT = 64

/**
 * Decoded blocks kept across probes. Too small a cache is far worse than
 * none at all: a search that keeps re-inflating the same blocks runs at a
 * fraction of its node rate. A search from a men-heavy root touches tens
 * of thousands of blocks, and the `endgame` benchmark shows where that
 * settles - at 24 MB it inflates some 13000 blocks a second, at 32 MB
 * almost none, and more than that buys nothing.
 */
const CACHE_BYTES = 32 << 20

type Table = {
  readonly id: number
  readonly slice: number
  readonly size: number
  readonly blockShift: number
  readonly blockMask: number
  readonly offsets: Uint32Array
  readonly data: Uint8Array
  /** Index layout: sizes of the four ranks, men first. */
  readonly nbm: number
  readonly nwk: number
  readonly nbk: number
  readonly wm: number
  readonly wk: number
  readonly bm: number
  readonly bk: number
}

const BINOM = buildBinomials()
const tables = new Map<number, Table>()
/** Decoded blocks by `table.id << 20 | block`, oldest first. */
const cache = new Map<number, Uint8Array>()
let maxPieces = 0
let limit = NO_LIMIT
let cachedBytes = 0
let nextId = 0
let probes = 0
let inflates = 0
let expected = 0
const misses = new Map<number, number>()
/* Last block read, the fast path: probes of one search cluster together. */
let lastTable: Table | null = null
let lastBlock = -1
let lastData: Uint8Array = new Uint8Array(0)

export type DbStats = {
  readonly probes: number
  /** Blocks inflated; far above one per block touched means thrashing. */
  readonly inflates: number
  readonly cachedBytes: number
}

/**
 * Slices a probe asked for and did not find, most asked for first, and
 * forgets them. A deep search misses every slice the position could be
 * traded down into, but it leans on a few of them far harder than on the
 * rest, and those are the ones worth fetching.
 */
export function dbMisses(): number[] {
  const out = [...misses.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([key]) => key)
  misses.clear()
  return out
}

/**
 * Material the probe should attempt even before its table is in, so that
 * a position out of reach of what is loaded is recorded as a miss rather
 * than passed over. The loader sets it from the manifest.
 */
export function dbExpect(pieces: number): void {
  expected = pieces
}

/** The four counts of a slice, as `dbMisses` reports them. */
export function sliceOf(key: number): {
  wm: number
  wk: number
  bm: number
  bk: number
} {
  return {
    wm: key & 15,
    wk: (key >>> 4) & 15,
    bm: (key >>> 8) & 15,
    bk: (key >>> 12) & 15,
  }
}

/** Counters since the tables were loaded; for the benchmarks. */
export function dbStats(): DbStats {
  return { probes, inflates, cachedBytes }
}

/**
 * Pieces on the board the tables can answer for: what is loaded, capped
 * by `dbLimit`. The cap is what lets one search play on four pieces while
 * another, in the same process, plays on six (`npm run selfplay`).
 */
export function dbPieces(): number {
  const range = maxPieces > expected ? maxPieces : expected
  return range < limit ? range : limit
}

/**
 * Caps the material the probe answers for; 0 switches it off. A search
 * that ran under a different cap left scores in the transposition table
 * that this one must not read, so a change clears it.
 */
export function dbLimit(pieces: number): void {
  if (pieces === limit) return
  limit = pieces
  ttClear()
}

export function dbClear(): void {
  tables.clear()
  cache.clear()
  maxPieces = 0
  limit = NO_LIMIT
  probes = 0
  inflates = 0
  expected = 0
  misses.clear()
  cachedBytes = 0
  nextId = 0
  lastTable = null
  lastBlock = -1
}

/**
 * Registers one slice file, as written by `dbgen -out`. Loading is the
 * caller's business: the worker fetches the files, the tests read them
 * from disk.
 */
export function dbAddSlice(bytes: Uint8Array): void {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)
  if (view.getUint32(0, true) !== MAGIC) throw new Error('not a table file')
  const slice = view.getUint32(4, true)
  const size = view.getUint32(8, true)
  const blockShift = view.getUint32(12, true)
  const blocks = view.getUint32(16, true)
  const offsets = new Uint32Array(blocks + 1)
  for (let i = 0; i <= blocks; i++)
    offsets[i] = view.getUint32(20 + i * 4, true)
  const head = 20 + (blocks + 1) * 4
  const wm = slice & 0xff
  const wk = (slice >>> 8) & 0xff
  const bm = (slice >>> 16) & 0xff
  const bk = (slice >>> 24) & 0xff
  tables.set(sliceKey(wm, wk, bm, bk), {
    id: nextId++,
    slice,
    size,
    blockShift,
    blockMask: (1 << blockShift) - 1,
    offsets,
    data: bytes.subarray(head),
    nbm: choose(28, bm),
    nwk: choose(32, wk),
    nbk: choose(32, bk),
    wm,
    wk,
    bm,
    bk,
  })
  const pieces = wm + wk + bm + bk
  if (pieces > maxPieces) maxPieces = pieces
  // Whatever the search decided without this slice it decided without
  // the truth, and those scores are in the table.
  ttClear()
}

/**
 * Score of the position for the side to move, or `DB_UNKNOWN` when its
 * slice is not loaded. The caller must have checked that the side to move
 * has no capture.
 */
export function dbProbe(
  white: number,
  black: number,
  kings: number,
  side: number,
  plies: number,
): number {
  let w = white
  let b = black
  let k = kings
  if (side !== WHITE) {
    w = reverse32(black)
    b = reverse32(white)
    k = reverse32(kings)
  }
  probes++
  const wMen = w & ~k
  const bMen = b & ~k
  const key = sliceKey(
    popcount(wMen),
    popcount(w & k),
    popcount(bMen),
    popcount(b & k),
  )
  const table = tables.get(key)
  if (table === undefined) {
    misses.set(key, (misses.get(key) ?? 0) + 1)
    return DB_UNKNOWN
  }
  let value: number
  try {
    value = valueAt(table, indexOf(table, w, b, k, wMen, bMen))
  } catch {
    // A file that arrived damaged would otherwise throw out of the middle
    // of the search and lose the move. The slice is dropped instead and
    // the search does what it did before the tables existed.
    drop(table)
    return DB_UNKNOWN
  }
  if (value === DB_DRAW) return DRAW_SCORE
  const budget = DRAW_PLIES - plies
  if (value < DB_LOSS_BASE) {
    return value <= budget ? DB_WIN - value : DRAW_SCORE
  }
  const threshold = value - DB_LOSS_BASE
  return threshold <= budget ? threshold - DB_WIN : DRAW_SCORE
}

/** Forgets one unreadable slice, and any block of it still cached. */
function drop(table: Table): void {
  tables.delete(sliceKey(table.wm, table.wk, table.bm, table.bk))
  for (const key of [...cache.keys()]) {
    if (key >>> 20 !== table.id) continue
    cachedBytes -= cache.get(key)!.length
    cache.delete(key)
  }
  lastTable = null
  lastBlock = -1
  maxPieces = 0
  for (const other of tables.values()) {
    const pieces = other.wm + other.wk + other.bm + other.bk
    if (pieces > maxPieces) maxPieces = pieces
  }
}

function sliceKey(wm: number, wk: number, bm: number, bk: number): number {
  return wm | (wk << 4) | (bm << 8) | (bk << 12)
}

/**
 * Index of a white-to-move position inside its slice, the same mixed
 * radix `dbgen` writes: men first, so one man placement is contiguous and
 * king moves only change the low digits.
 */
function indexOf(
  table: Table,
  w: number,
  b: number,
  k: number,
  wMen: number,
  bMen: number,
): number {
  const wmRank = rank(wMen, 0, table.wm)
  const bmRank = rank(bMen, 4, table.bm)
  const wkRank = rank(w & k, 0, table.wk)
  const bkRank = rank(b & k, 0, table.bk)
  return (
    ((wmRank * table.nbm + bmRank) * table.nwk + wkRank) * table.nbk + bkRank
  )
}

/**
 * Colexicographic rank of the squares of `sub` inside a domain that
 * starts at `offset`; `n` is how many squares are set.
 */
function rank(sub: number, offset: number, n: number): number {
  let r = 0
  let i = 1
  for (let rest = sub; rest !== 0; rest &= rest - 1) {
    r += choose(lsb(rest) - offset, i)
    i++
  }
  if (i !== n + 1) throw new Error('piece count does not match the slice')
  return r
}

function valueAt(table: Table, index: number): number {
  const block = index >>> table.blockShift
  if (table === lastTable && block === lastBlock) {
    return lastData[index & table.blockMask]!
  }
  const key = (table.id << 20) | block
  let data = cache.get(key)
  if (data === undefined) {
    const size = 1 << table.blockShift
    inflates++
    data = new Uint8Array(size)
    const written = inflateRaw(
      table.data.subarray(table.offsets[block]!, table.offsets[block + 1]!),
      data,
    )
    // A block that inflates short leaves zeros behind it, and a zero is a
    // draw rather than an error; only the full block is believable. The
    // last one holds what is left of the slice.
    const rest = table.size - (block << table.blockShift)
    if (written !== (rest < size ? rest : size)) {
      throw new Error(`endgame block ${block} inflated to ${written} bytes`)
    }
    cache.set(key, data)
    cachedBytes += size
    // A Map keeps insertion order, so the first key is the block that has
    // been in the cache longest.
    while (cachedBytes > CACHE_BYTES && cache.size > 1) {
      const oldest = cache.keys().next()
      if (oldest.done === true) break
      cachedBytes -= cache.get(oldest.value)!.length
      cache.delete(oldest.value)
      lastBlock = -1
    }
  }
  lastTable = table
  lastBlock = block
  lastData = data
  return data[index & table.blockMask]!
}

function choose(n: number, k: number): number {
  if (k < 0 || n < 0 || k > n) return 0
  return BINOM[n * 33 + k]!
}

function buildBinomials(): Int32Array {
  const binom = new Int32Array(33 * 33)
  for (let n = 0; n < 33; n++) {
    binom[n * 33] = 1
    for (let k = 1; k <= n; k++) {
      binom[n * 33 + k] =
        binom[(n - 1) * 33 + k - 1]! + binom[(n - 1) * 33 + k]!
    }
  }
  return binom
}
